site_name: OWASP Mobile Application Security
repo_url: https://github.com/OWASP/owasp-mastg
repo_name: OWASP/owasp-mastg
# use_directory_urls: false # only set for mkdocs build

# https://www.mkdocs.org/user-guide/configuration/#validation
# due to our use of mkdocs-awesome-pages-plugin, we need to ignore absolute links for nav
validation:
  nav:
    absolute_links: ignore

nav:
  - Home: index.md
  - "MASWE (Beta)": 
    - MASWE/index.md
    - MASVS-STORAGE:
      - ... | flat | MASWE/MASVS-STORAGE/*.md
    - MASVS-CRYPTO:
      - ... | flat | MASWE/MASVS-CRYPTO/*.md
    - MASVS-AUTH:
      - ... | flat | MASWE/MASVS-AUTH/*.md
    - MASVS-NETWORK:
      - ... | flat | MASWE/MASVS-NETWORK/*.md
    - MASVS-PLATFORM:
      - ... | flat | MASWE/MASVS-PLATFORM/*.md
    - MASVS-CODE:
      - ... | flat | MASWE/MASVS-CODE/*.md
    - MASVS-RESILIENCE:
      - ... | flat | MASWE/MASVS-RESILIENCE/*.md
    - MASVS-PRIVACY:
      - ... | flat | MASWE/MASVS-PRIVACY/*.md

  - MASTG:
      - MASTG/index.md
      - Intro:
        - ... | flat | MASTG/0x0[1-2]*.md # Overview of the project (0x03) is redundant in the web.
        - ... | flat | MASTG/0x09*.md
      - General Concepts:
        - ... | flat | MASTG/0x04*.md
      - Android Security Testing:
        - ... | flat | MASTG/0x05*.md
      - iOS Security Testing: 
        - ... | flat | MASTG/0x06*.md
      - Best Practices:
        - MASTG/best-practices/index.md
        - ... | flat | MASTG/best-practices/*.md
      - Tests:
        - MASTG/tests/index.md
        - Android:
          - MASVS-STORAGE:
            - ... | flat | MASTG/tests/android/MASVS-STORAGE/*.md
          - MASVS-CRYPTO:
            - ... | flat | MASTG/tests/android/MASVS-CRYPTO/*.md
          - MASVS-AUTH:
            - ... | flat | MASTG/tests/android/MASVS-AUTH/*.md
          - MASVS-NETWORK:
            - ... | flat | MASTG/tests/android/MASVS-NETWORK/*.md
          - MASVS-PLATFORM:
            - ... | flat | MASTG/tests/android/MASVS-PLATFORM/*.md
          - MASVS-CODE:
            - ... | flat | MASTG/tests/android/MASVS-CODE/*.md
          - MASVS-RESILIENCE:
            - ... | flat | MASTG/tests/android/MASVS-RESILIENCE/*.md
          - MASVS-PRIVACY:
            - ... | flat | MASTG/tests/android/MASVS-PRIVACY/*.md
        - iOS:
          - MASVS-STORAGE:
            - ... | flat | MASTG/tests/ios/MASVS-STORAGE/*.md
          - MASVS-CRYPTO:
            - ... | flat | MASTG/tests/ios/MASVS-CRYPTO/*.md
          - MASVS-AUTH:
            - ... | flat | MASTG/tests/ios/MASVS-AUTH/*.md
          - MASVS-NETWORK:
            - ... | flat | MASTG/tests/ios/MASVS-NETWORK/*.md
          - MASVS-PLATFORM:
            - ... | flat | MASTG/tests/ios/MASVS-PLATFORM/*.md
          - MASVS-CODE:
            - ... | flat | MASTG/tests/ios/MASVS-CODE/*.md
          - MASVS-RESILIENCE:
            - ... | flat | MASTG/tests/ios/MASVS-RESILIENCE/*.md
          - MASVS-PRIVACY:
            - ... | flat | MASTG/tests/ios/MASVS-PRIVACY/*.md
      - Demos:
        - MASTG/demos/index.md
        - Android:
          - MASVS-STORAGE:
            - ... | flat | MASTG/demos/android/MASVS-STORAGE/**/MASTG-DEMO-*.md
          - MASVS-CRYPTO:
            - ... | flat | MASTG/demos/android/MASVS-CRYPTO/**/MASTG-DEMO-*.md
          # - MASVS-AUTH:
          #   - ... | flat | MASTG/demos/android/MASVS-AUTH/**/MASTG-DEMO-*.md
          - MASVS-NETWORK:
            - ... | flat | MASTG/demos/android/MASVS-NETWORK/**/MASTG-DEMO-*.md
          - MASVS-PLATFORM:
            - ... | flat | MASTG/demos/android/MASVS-PLATFORM/**/MASTG-DEMO-*.md
          - MASVS-CODE:
            - ... | flat | MASTG/demos/android/MASVS-CODE/**/MASTG-DEMO-*.md
          - MASVS-RESILIENCE:
            - ... | flat | MASTG/demos/android/MASVS-RESILIENCE/**/MASTG-DEMO-*.md
          - MASVS-PRIVACY:
            - ... | flat | MASTG/demos/android/MASVS-PRIVACY/**/MASTG-DEMO-*.md
        - iOS:
          - MASVS-STORAGE:
            - ... | flat | MASTG/demos/ios/MASVS-STORAGE/**/MASTG-DEMO-*.md
          - MASVS-CRYPTO:
            - ... | flat | MASTG/demos/ios/MASVS-CRYPTO/**/MASTG-DEMO-*.md
          - MASVS-AUTH:
            - ... | flat | MASTG/demos/ios/MASVS-AUTH/**/MASTG-DEMO-*.md
          # - MASVS-NETWORK:
          #   - ... | flat | MASTG/demos/ios/MASVS-NETWORK/**/MASTG-DEMO-*.md
          # - MASVS-PLATFORM:
          #   - ... | flat | MASTG/demos/ios/MASVS-PLATFORM/**/MASTG-DEMO-*.md
          # - MASVS-CODE:
          #   - ... | flat | MASTG/demos/ios/MASVS-CODE/**/MASTG-DEMO-*.md
          - MASVS-RESILIENCE:
            - ... | flat | MASTG/demos/ios/MASVS-RESILIENCE/**/MASTG-DEMO-*.md
          # - MASVS-PRIVACY:
          #   - ... | flat | MASTG/demos/ios/MASVS-PRIVACY/**/MASTG-DEMO-*.md
      - Techniques:
        - MASTG/techniques/index.md
        - Generic:
          - ... | flat | MASTG/techniques/generic/*.md
        - Android:
          - ... | flat | MASTG/techniques/android/*.md
        - iOS:
          - ... | flat | MASTG/techniques/ios/*.md
      - Tools:
        - MASTG/tools/index.md
        - Generic:
          - ... | flat | MASTG/tools/generic/*.md
        - Android:
          - ... | flat | MASTG/tools/android/*.md
        - iOS:
          - ... | flat | MASTG/tools/ios/*.md
        - Network:
          - ... | flat | MASTG/tools/network/*.md
      - Apps:
        - MASTG/apps/index.md
        - Android:
          - ... | flat | MASTG/apps/android/*.md
        - iOS:
          - ... | flat | MASTG/apps/ios/*.md

  - MASVS:
      - MASVS/index.md
      - Intro:
        - ... | flat | MASVS/0[1-4]*.md
      - MASVS-STORAGE: MASVS/05-MASVS-STORAGE.md
      - ... | flat | MASVS/controls/MASVS-STORAGE*.md
      - MASVS-CRYPTO: MASVS/06-MASVS-CRYPTO.md
      - ... | flat | MASVS/controls/MASVS-CRYPTO*.md
      - MASVS-AUTH: MASVS/07-MASVS-AUTH.md
      - ... | flat | MASVS/controls/MASVS-AUTH*.md
      - MASVS-NETWORK: MASVS/08-MASVS-NETWORK.md
      - ... | flat | MASVS/controls/MASVS-NETWORK*.md
      - MASVS-PLATFORM: MASVS/09-MASVS-PLATFORM.md
      - ... | flat | MASVS/controls/MASVS-PLATFORM*.md
      - MASVS-CODE: MASVS/10-MASVS-CODE.md
      - ... | flat | MASVS/controls/MASVS-CODE*.md
      - MASVS-RESILIENCE: MASVS/11-MASVS-RESILIENCE.md
      - ... | flat | MASVS/controls/MASVS-RESILIENCE*.md
      - MASVS-PRIVACY: MASVS/12-MASVS-PRIVACY.md
      - ... | flat | MASVS/controls/MASVS-PRIVACY*.md
  - "MAS Checklist":
     - checklists/index.md
     - MASVS-STORAGE: checklists/MASVS-STORAGE.md
     - MASVS-CRYPTO: checklists/MASVS-CRYPTO.md 
     - MASVS-AUTH: checklists/MASVS-AUTH.md
     - MASVS-NETWORK: checklists/MASVS-NETWORK.md
     - MASVS-PLATFORM: checklists/MASVS-PLATFORM.md
     - MASVS-CODE: checklists/MASVS-CODE.md
     - MASVS-RESILIENCE: checklists/MASVS-RESILIENCE.md
     - MASVS-PRIVACY: checklists/MASVS-PRIVACY.md
  - "MAS Crackmes": 
      - crackmes/index.md
      - ... | flat | crackmes/*.md
  - News:
      - news/index.md
  - talks.md
  - "&#11088; Contribute":
      - contributing/index.md
      - ... | flat | contributing/*.md
  - "&#128153; Donate":
      - donate.md
      - ... | flat | donate/*.md
  - contact.md

copyright: |
  <div style="float: left; padding-right: 1em;">
    <a href="https://www.owasp.org"><img src="https://github.com/OWASP/owasp-mastg/blob/master/Document/Images/OWASP_logo_white.png?raw=true" width="100px" /></a>
  </div>
  <span style="font-size: smaller">
    &#169; OWASP Foundation 2025. This work is licensed under 
    <a href="https://creativecommons.org/licenses/by/4.0">CC-BY-4.0</a>. For any reuse or distribution, you must make clear to others the license terms of this work.
  </span><br><span style="font-size: smaller">OWASP &#174; is a registered trademark of the OWASP Foundation, Inc.</span> <span style="font-size: smaller">This website uses cookies to analyze our traffic and only share that information with our analytics partners. <a href="https://github.com/OWASP/owasp-mastg/blob/master/about_cookies.md">Learn more</a>.</span>
  <div style="color: #6a6868; font-size: smaller"><span>Made with</span> <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>  | <i>Website and covers designed by Carlos Holguera.</i></div>

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_circle.png
  favicon: assets/logo_circle.png
  icon:
    repo: fontawesome/brands/github
    tag:
      android: material/android
      ios: material/apple
      network: material/web
      p: material/eye-circle-outline
      l1: material/circle
      l2: material/circle-multiple-outline
      r: material/circle-double
      placeholder: material/pencil-plus
      update-pending: material/information-outline
      deprecated: octicons/circle-slash-16
      new: material/alert-decagram
      tool: octicons/tools-24
      test: octicons/codescan-checkmark-24
      app: octicons/code-square-24
      demo: material/flask-outline
      tech: material/magic-staff # fontawesome/solid/wand-magic-sparkles
      best: material/shield-check
      maswe: octicons/shield-24
      masvs: simple/owasp
      masvs-storage: simple/owasp
      masvs-crypto: simple/owasp
      masvs-auth: simple/owasp
      masvs-network: simple/owasp
      masvs-platform: simple/owasp
      masvs-code: simple/owasp
      masvs-resilience: simple/owasp
      masvs-privacy: simple/owasp

  features:
    - search.suggest
    - search.share
    # - toc.integrate
    - navigation.instant
    # - navigation.prune
    # - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
    - content.action.edit

  palette:
    # - primary: #499FFF 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css
extra_javascript:
  - javascripts/external_links.js
  - https://code.jquery.com/jquery-3.5.1.js
  - https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js
  - javascripts/datatables.js
  - javascripts/filter_tests.js
  - javascripts/navigation.js
  - javascripts/tags.js
plugins:
  # Uses https://github.com/mkdocs/mkdocs-redirects getting the redirects map from src/scripts/generate_redirects.py
  - search
  - awesome-pages
  # - privacy
  # - offline
  - blog:
  # https://squidfunk.github.io/mkdocs-material/plugins/blog/
      blog_dir: news
      pagination_per_page: 10
      post_excerpt_max_authors: 2
  - tags
      # tags_file: tags.md # TODO: bug in mkdocs? dynamic tags from hooks not appearing in tags.md
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: false
      base_path:
        - !relative # allows to include snippets from the same folder
        # - docs/MASTG/ # alternative to include snippets from specific folders
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

hooks:
  # General
  - docs/hooks/edit_button_uri.py

  # Priority -30 for extracting the ID for old tests. Also assigns icons to pages so they show up in navigation
  - docs/hooks/extract-id-from-path.py

  # Priority -40 for adding content
  - docs/hooks/add-checklists-banner.py
  - docs/hooks/add-cross-references.py
  - docs/hooks/replace_snippets.py
  - docs/hooks/maswe-beta-banner.py
  - docs/hooks/create_dynamic_tables.py

  # Priority -49 for last-minute tag modification
  - docs/hooks/add-tags.py
  - docs/hooks/update_titles.py
  - docs/hooks/update_git_info.py

  # Priority -50 for conversion of tags and cross-references
  - docs/hooks/resolve_references.py

extra:
  generator: false # removed but recreated in copyright above
  analytics:
    provider: google
    property: G-KWZRJV0S4P
  social:
    - icon: fontawesome/brands/slack
      link: https://owasp.slack.com/archives/C1M6ZVC6S
    - icon: fontawesome/brands/bluesky 
      link: https://bsky.app/profile/owasp-mas.bsky.social
    - icon: fontawesome/brands/mastodon 
      link: https://infosec.exchange/@OWASP_MAS
    - icon: fontawesome/brands/github
      link: https://github.com/OWASP/owasp-mastg/discussions
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:carlos.holguera@owasp.org
    #   name: Carlos Holguera
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:sven.schleier@owasp.org
    #   name: Sven Schleier
  tags:
    android: android
    ios: ios
    network: network
    P: p
    L1: l1
    L2: l2
    R: r
    placeholder: placeholder
    update-pending: update-pending
    deprecated: deprecated
    new: new
    tool: tool
    test: test
    app: app
    demo: demo
    tech: tech
    maswe: maswe
    placeholder-tag-maswe: maswe
    placeholder-tag-test: test
    placeholder-tag-tech: tech
    placeholder-tag-demo: demo
    placeholder-tag-app: app
    placeholder-tag-tool: tool

    masvs-storage-1: masvs-storage
    masvs-storage-2: masvs-storage
    masvs-crypto-1: masvs-crypto
    masvs-crypto-2: masvs-crypto
    masvs-auth-1: masvs-auth
    masvs-auth-2: masvs-auth
    masvs-auth-3: masvs-auth
    masvs-network-1: masvs-network
    masvs-network-2: masvs-network
    masvs-platform-1: masvs-platform
    masvs-platform-2: masvs-platform
    masvs-platform-3: masvs-platform
    masvs-code-1: masvs-code
    masvs-code-2: masvs-code
    masvs-code-3: masvs-code
    masvs-code-4: masvs-code
    masvs-resilience-1: masvs-resilience
    masvs-resilience-2: masvs-resilience
    masvs-resilience-3: masvs-resilience
    masvs-resilience-4: masvs-resilience
    masvs-privacy-1: masvs-privacy
    masvs-privacy-2: masvs-privacy
    masvs-privacy-3: masvs-privacy
    masvs-privacy-4: masvs-privacy
    masvs: masvs
    best: best
  status:
    placeholder: This page is a placeholder.
    deprecated: This page is deprecated.
    new: This page is new!
    update-pending: This page is pending an update.
