name: Build Website (Reusable)
on:
  workflow_call:
    inputs:
      deploy:
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python virtual environment and install dependencies
        uses: getsentry/action-setup-venv@v2.1.1
        id: venv
        with:
          python-version: 3.x 
          cache-dependency-path: src/scripts/requirements.txt
          install-cmd: pip install -r src/scripts/requirements.txt

      - uses: actions/checkout@v4
        with:
          repository: "OWASP/maswe"
          fetch-depth: 1
          path: maswe/
      - run: bash -x ./src/scripts/structure_maswe.sh

      - run: bash -x ./src/scripts/structure_mastg.sh

      - name: Get Latest MASVS Release Tag
        run: echo "MASVS_VERSION=$(curl -s https://api.github.com/repos/OWASP/masvs/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: "OWASP/masvs"
          fetch-depth: 1
          path: masvs/
      - name: Generate MASVS yaml
        run: python3 ./masvs/tools/generate_masvs_yaml.py -v ${{env.MASVS_VERSION}} -i ./masvs/Document -c ./masvs/controls
      - name: Populate MASVS Categories Markdown Files
        run: python3 ./masvs/tools/populate_masvs_categories_md.py -d ./masvs/Document -w
      - run: ./src/scripts/structure_masvs.sh

      - name: Generate MASVS Control Markdown Files
        run: python3 src/scripts/write_masvs_control_md_files.py
      
      - name: Build website (no deploy)
        if: ${{ !inputs.deploy }}
        run: mkdocs build --clean --verbose

      - name: Deploy to GitHub Pages
        if: ${{ inputs.deploy }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force --clean --verbose
