name: Build GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt

      - name: Assemble Testing Chapters
        run: python3 tools/scripts/assemble_test_chapters.py -w

      - run: ./tools/scripts/structure_mastg.sh
      - run: python3 tools/scripts/transform_files.py

      - run: mv Document/Images/ docs/assets/Images/
      - run: sed -i "s#<img src=\"Images/#<img src=\"../../../assets/Images/#g" docs/MASTG/**/*.md

      - uses: actions/checkout@v3
        with:
          repository: "OWASP/owasp-masvs"
          fetch-depth: 1
          path: owasp-masvs/
      - run: ./tools/scripts/structure_masvs.sh
      - run: mkdir docs/assets/Images/MASVS
      - run: mv owasp-masvs/Document/images/* docs/assets/Images/MASVS
      - run: sed -i "s#images/#../../assets/Images/MASVS/#g" docs/MASVS/**/*.md
      
      - run: mkdir docs/MASTG/tests
      - run: find tests -type f -exec cp {} docs/MASTG/tests \;
      - run: python3 tools/scripts/populate_dynamic_pages.py
      
      - run: mkdocs gh-deploy --force --clean --verbose
