name: Documents Build

on: [push, workflow_dispatch]

jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set VERSION to env 
      run: echo "VERSION=$(curl -s https://api.github.com/repos/OWASP/owasp-mstg/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_ENV

    - name: Set DEV VERSION if it's not a tag
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: echo "VERSION=${{env.VERSION}}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Generate English PDF
      run: ./tools/docker/pandoc_makedocs.sh Document ${{env.VERSION}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MSTG-${{env.VERSION}}
        path: OWASP_MSTG-${{env.VERSION}}*

  release:
    runs-on: ubuntu-latest
    needs: [generate]
    if: startsWith(github.ref, 'refs/tags/') && (github.actor == 'cpholguera' || github.actor == 'sushi2k')
    steps:
      - uses: actions/download-artifact@v2
      - name: List Downloaded document (sampling of download-artifact)
        run: ls -l OWASP_MSTG*
      # - name: Move all documents (pdf, epub and docx) to root
      #   run: mv OWASP_MSTG-*-*/* .
      # Produces error: 
      #   mv: cannot stat 'OWASP_MSTG-*-*/*': No such file or directory
      #   Error: Process completed with exit code 1.
      - name: print working directory
        run: pwd 
      - name: Listing of root directory
        run: ls -l 

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: true
          generate_release_notes: true
          discussion_category_name: Announcements
          files: |
            OWASP_MSTG-*/OWASP_MSTG-*.pdf
            OWASP_MSTG-*/OWASP_MSTG-*.epub
            OWASP_MSTG-*/OWASP_MSTG-*.docx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
